### ISSUE TITLE
The application crashes when I click on the Settings button

### ISSUE THREAD

**Issue by friendsmobile** [ohmae/voice-message-board#10]
# Project Information
 
* Repository: https://github.com/ohmae/voice-message-board
* Project Name: Voice Message Board
* My Github Account: https://github.com/friendsmobile

# Expected behavior

When I click on the Settings button, all options in the Settings button should be displayed so that the user can easily use it.

# Actual behavior

After I open the application, the app crashes when I click the setting option.

# How to reproduce

* [Download ](https://play.google.com/store/apps/details?id=net.mm2d.android.vmb) the app 
* At the top right click on the 3 vertical line
* Click the setting option
* Note the BUG

* Browser/App version:  v 1.5.1
* Operating system: 6.0

# Recording Of The Bug

![20190601_163824](https://user-images.githubusercontent.com/51118734/58747984-3b993c80-8427-11e9-84e9-57989062c120.gif)

# Logcat

<pre><code>E/AndroidRuntime(30459): FATAL EXCEPTION: main

E/AndroidRuntime(30459): Process: net.mm2d.android.vmb, PID: 30459

E/AndroidRuntime(30459): android.view.InflateException: Binary XML file line #20: Error inflating class androidx.appcompat.widget.SwitchCompat

E/AndroidRuntime(30459): 	at android.view.LayoutInflater.createView(LayoutInflater.java:633)

E/AndroidRuntime(30459): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)

E/AndroidRuntime(30459): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:482)

E/AndroidRuntime(30459): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)

E/AndroidRuntime(30459): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:365)

E/AndroidRuntime(30459): 	at androidx.preference.h.a(PreferenceGroupAdapter.java:14369)

E/AndroidRuntime(30459): 	at androidx.recyclerview.widget.RecyclerView$a.b(RecyclerView.java:6794)

E/AndroidRuntime(30459): 	at androidx.recyclerview.widget.RecyclerView$o.a(RecyclerView.java:5975)

E/AndroidRuntime(30459): 	at androidx.recyclerview.widget.RecyclerView$o.b(RecyclerView.java:5858)

E/AndroidRuntime(30459): 	at androidx.recyclerview.widget.LinearLayoutManager$c.a(LinearLayoutManager.java:11854)

E/AndroidRuntime(30459): 	at androidx.recyclerview.widget.LinearLayoutManager.a(LinearLayoutManager.java:1557)

E/AndroidRuntime(30459): 	at androidx.recyclerview.widget.LinearLayoutManager.a(LinearLayoutManager.java:1517)

E/AndroidRuntime(30459): 	at androidx.recyclerview.widget.LinearLayoutManager.c(LinearLayoutManager.java:612)

E/AndroidRuntime(30459): 	at androidx.recyclerview.widget.RecyclerView.E(RecyclerView.java:3924)

E/AndroidRuntime(30459): 	at androidx.recyclerview.widget.RecyclerView.z(RecyclerView.java:3641)

E/AndroidRuntime(30459): 	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4194)

E/AndroidRuntime(30459): 	at android.view.View.layout(View.java:16075)

E/AndroidRuntime(30459): 	at android.view.ViewGroup.layout(ViewGroup.java:5300)

E/AndroidRuntime(30459): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)

E/AndroidRuntime(30459): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)

E/AndroidRuntime(30459): 	at android.view.View.layout(View.java:16075)

E/AndroidRuntime(30459): 	at android.view.ViewGroup.layout(ViewGroup.java:5300)

E/AndroidRuntime(30459): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)

E/AndroidRuntime(30459): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)

E/AndroidRuntime(30459): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)

E/AndroidRuntime(30459): 	at android.view.View.layout(View.java:16075)

E/AndroidRuntime(30459): 	at android.view.ViewGroup.layout(ViewGroup.java:5300)

E/AndroidRuntime(30459): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)

E/AndroidRuntime(30459): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)

E/AndroidRuntime(30459): 	at android.view.View.layout(View.java:16075)

E/AndroidRuntime(30459): 	at android.view.ViewGroup.layout(ViewGroup.java:5300)

E/AndroidRuntime(30459): 	at androidx.appcompat.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:444)

E/AndroidRuntime(30459): 	at android.view.View.layout(View.java:16075)

E/AndroidRuntime(30459): 	at android.view.ViewGroup.layout(ViewGroup.java:5300)

E/AndroidRuntime(30459): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)

E/AndroidRuntime(30459): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)

E/AndroidRuntime(30459): 	at android.view.View.layout(View.java:16075)

E/AndroidRuntime(30459): 	at android.view.ViewGroup.layout(ViewGroup.java:5300)

E/AndroidRuntime(30459): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)

E/AndroidRuntime(30459): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)

E/AndroidRuntime(30459): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)

E/AndroidRuntime(30459): 	at android.view.View.layout(View.java:16075)

E/AndroidRuntime(30459): 	at android.view.ViewGroup.layout(ViewGroup.java:5300)

E/AndroidRuntime(30459): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)

E/AndroidRuntime(30459): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)

E/AndroidRuntime(30459): 	at android.view.View.layout(View.java:16075)

E/AndroidRuntime(30459): 	at android.view.ViewGroup.layout(ViewGroup.java:5300)

E/AndroidRuntime(30459): 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2119)

E/AndroidRuntime(30459): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1873)

E/AndroidRuntime(30459): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1073)

E/AndroidRuntime(30459): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5988)

E/AndroidRuntime(30459): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)

E/AndroidRuntime(30459): 	at android.view.Choreographer.doCallbacks(Choreographer.java:580)

E/AndroidRuntime(30459): 	at android.view.Choreographer.doFrame(Choreographer.java:550)

E/AndroidRuntime(30459): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)

E/AndroidRuntime(30459): 	at android.os.Handler.handleCallback(Handler.java:739)

E/AndroidRuntime(30459): 	at android.os.Handler.dispatchMessage(Handler.java:95)

E/AndroidRuntime(30459): 	at android.os.Looper.loop(Looper.java:135)

E/AndroidRuntime(30459): 	at android.app.ActivityThread.main(ActivityThread.java:5910)

E/AndroidRuntime(30459): 	at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime(30459): 	at java.l
</code></pre>

**Comment by ohmae** [comment]
I know it from the crash log, but I can not reproduce it.
But it would be fixed by https://github.com/ohmae/voice-message-board/commit/1e578684e2f4e27d1d8e362294e8ce692e3bfcd6

**Comment by friendsmobile** [comment]
okay sir thanks you
