### ISSUE TITLE
Allow more words rcorgnition flexibility, sharing and copying of words on board.

### ISSUE THREAD

**Issue by cckole** [ohmae/voice-message-board#11]
I love voice message board and I would love to give some comments and Idea to make it more unique.

This wonderful app displays voice words on board and I love how nice it reads voice with a reasonable percent accuracy. That said, I would love it to allow `more words recorgnition flexibility`. currently, it works in a way that when one takes a breath for 5 seconds, it stops the voice message recorgnition. What if there is an option to set the lenght of time. 
- Default settings which will be the way the app is currently set to magnetize words and display it on board and
- A new way to make it allow word recorgnition until the user halts. This way, anyone using voice message board will be able to record voice at lenght.

More so, a share feature will make sense on it. Any message voiced on the board will be shared to other people through different channels like facebook, whatsapp, twitter and so on. Making the displayed words on board highlightable to enable copying will also make a lot of sense for an app like this. I would love to see all these on this wonderful app. Apparently, all the current features are fantastic. Adding more will make it user friendly and it will serve more purpose as well. Thumbs up to the PO. 
Thanks for the good work.

**Comment by ohmae** [comment]
Thanks
I use Google's API that can be used free of charge for voice recognition, but it is too restrictive and I can not set it freely. In the future, a more flexible API may be provided, so I will consider it at that time.
And I think the share feature is a little different from the purpose of this app. But I think it is a good idea to make effective use of voice-recognized strings. I take it into consideration.

**Comment by ohmae** [comment]
I added share function https://github.com/ohmae/voice-message-board/commit/95a7c1965170665aba8deb84c5109c76e78d6ee6
And make text selectable https://github.com/ohmae/voice-message-board/commit/07d1586d426422ec70c6c6f13ff438547d24adc9

**Comment by cckole** [comment]
Oh! That is so fast.. Thanks for considering my proposals.
