### ISSUE TITLE
Voice message board v1.4.2 | speech feature is broken when switching to landscape mode

### ISSUE THREAD

**Issue by Icramss** [ohmae/voice-message-board#8]
# Expected behavior

The speech feature should still work when switching to landscape mode

# Actual behavior

When switching to landscape mode, the Speech feature is broken and no longer works

# How to reproduce

- Download app on playstore
- Open the app
- click on "TAP HERE" to talk
- please speak in portrait mode and  get the result
- wait a moment and please switch to landscape mode
- please talk, it does not work anymore

### Device: ONE PLUS 2 OxygenOS Version 3.6.1
Operating System:Android 6.0.1
App Version :1.4.2

# Recording of the bug

https://youtu.be/8Odr4DYplNc

**Comment by ohmae** [comment]
Fixed. https://github.com/ohmae/VoiceMessageBoard/commit/8f8363b1c64ee0150a879fa1c0f7613c59460c54
Wait a while for the release.

**Comment by Icramss** [comment]
Is this a bug of this application!?
